version: 0.2

phases:
  install:
    commands:
      - apt-get update
#      - apt-get upgrade -y
      - apt-get install python3-pip -y
      - pip3 install checkov
  build:
    commands:
      - checkov -d terraform-example/
